const base = "/images/imported";

export const personImages: Record<string, string> = {
  "Animesh Kujur": `${base}/ANIMESH-KUJUR.jpg`,
  "Ankita Dhyani": `${base}/ANKITA-DHYANI.webp`,
  "Ayush Shetty": `${base}/AYUSH-SHETTY.jpg`,
  "C. Ajithkumar": `${base}/C-AJITHKUMAR.png`,
  "Deepa Grace Ekka": `${base}/DEEPA-GRACE-EKKA.jpg`,
  "Hari Prasad Pattnayak": `${base}/HARI-PRASAD-PATTNAYAK.avif`,
  "Indian Women Ice Hockey Team": `${base}/INDIAN-WOMEN-ICE-HOCKEY-TEAM.jpg`,
  "Jyothi Yarraji": `${base}/JYOTHI-YARRAJI.jpg`,
  "Neeraj Jha": `${base}/NEERAJ-JHA.jpg`,
  "Nithya Gandhe": `${base}/Nithya-gandhe.jpg`,
  "O P Singh Karhana": `${base}/O-P-SINGH-KARHANA.jpg`,
  "Rahul Banerjee": `${base}/RAHUL-BANERJEE.png`,
  "Ruhaan Alva": `${base}/RUHAAN-ALVA-1.png`,
  "Sajan Prakash": `${base}/SAJAN-PRAKASH.jpg`,
  "Samardeep Singh": `${base}/SAMARDEEP-SINGH.webp`,
  "Sarthak Chavan": `${base}/SARTHAK-CHAVAN.jpg`,
  "Sarthak Kamal": `${base}/SARTHAK-KAMAL.jpg`,
  "Satwiksairaj Rankireddy": `${base}/satwiksairaj-rankireddy.jpg`,
  "Siksha Jain": `${base}/SIKSHA-JAIN.jpg`,
  "Tapan Mohanty": `${base}/TAPAN-MOHANTY.jpg`,
  "Vikash Thakur": `${base}/VIKASH-THAKUR.webp`,
  "Wasim Jaffer": `${base}/WASIM-JAFFER.jpg`,
  "Dilip Tirkey": `${base}/DILIP-TIRKEY.jpg`,
  "Dilip Kumar Tirkey": `${base}/Whats-App-Image-2025-08-24-at-12-53-12-AM.jpg`,
  "Shri Dilip Kumar Tirkey": `${base}/Whats-App-Image-2025-08-24-at-12-53-12-AM.jpg`,
  "Manikanta H Hoblidhar": `${base}/MANIKANTA-H-HOBLIDHAR.jpg`,
  "Odisha Women Football Team": `${base}/ODISHA-WOMEN-FOOTBALL-TEAM.jpg`,
  "Odisha Women's Football Team": `${base}/footballteam-1024x847.jpg`,
  "Sandeep Sejwal": `${base}/SANDEEP-SEJWAL.jpg`,
  "Srabani Nanda": `${base}/srabani-nanda-1024x846.jpg`,
  "Swasti Singh": `${base}/swasti-1024x847.jpg`,
  "Col Devidutta Panda": `${base}/COL-DEVIDUTTA-PANDA.jpg`,
  "Pranati Nayak": `${base}/PRANATI-NAYAK.jpg`,
  "Sandeep Kumar": `${base}/SANDEEP-KUMAR.jpg`,
  "Satish Shivalingam": `${base}/SATISH-SHIVALINGAM.jpg`,
  "Thakur Aditya": `${base}/THAKUR-ADITYA.jpg`,
  "Vimal Kumar": `${base}/VIMAL-KUMAR.jpg`,
  "Lalu Prasad Bhoi": `${base}/Lalu-Prasad-bhoi.jpg`,
  "K. Malleswari": `${base}/K-malleswari.jpg`,
  "Karnam Malleswari": `${base}/K-malleswari.jpg`,
  "Indian Men's Hockey Team": `${base}/Indian-hockey-team-men.jpg`,
  "Bruno Cuntinho": `${base}/Bruno-cuntinho.jpg`,
  "Bruno Coutinho": `${base}/BRUNO.jpg`,
  "Abdul Hakim Giri": `${base}/Abdul-hakim-giri.jpg`,
  "Aditya Thakur": `${base}/aditya-thakur.jpg`,
  "Aneesh S. Gowda": `${base}/ANEES.jpg`,
  "Diptiranjan Samal": `${base}/DIPTI.jpg`,
  "Manikanta Hoblidhar": `${base}/manikanta-1024x848.jpg`,
  "Ram Bahadur Subba": `${base}/ram-1024x843.jpg`,
  "Odisha Mining Corporation": `${base}/omc-1024x842.jpg`,
  "Ardor Football Academy": `${base}/ardor-1024x847.jpg`,
  "Brahmanand Sankhwalkar": `${base}/brahamanand-1024x849.jpg`,
  "Dr. Prabodh Mohanty": `${base}/Whats-App-Image-2025-08-24-at-12-51-36-AM.jpg`,
  "Prabodh Mohanty": `${base}/Whats-App-Image-2025-08-24-at-12-51-36-AM.jpg`,
  "Shri Probodh Mohanty": `${base}/Whats-App-Image-2025-08-24-at-12-51-36-AM.jpg`,
  "Rajaraman": `${base}/Whats-App-Image-2025-08-24-at-12-45-12-AM.jpg`,
  "U. Vimal Kumar": `${base}/Whats-App-Image-2025-08-24-at-12-49-27-AM.jpg`,
  "Pritveen Rajan": `${base}/Whats-App-Image-2025-08-24-at-12-53-55-AM.jpg`,
  "Dr. Sarthak Patnaik": `${base}/Whats-App-Image-2025-07-04-at-11-29-11-579ed221-2-745x1024.jpg`,
  "Sarthak Patnaik": `${base}/Whats-App-Image-2025-07-04-at-11-29-11-579ed221-2-745x1024.jpg`,
  "Mr. Soumya Patnaik": `${base}/1-768x1024.jpg`,
  "Soumya Patnaik": `${base}/1-768x1024.jpg`,
  "Dr. Nisha Kaushik": `${base}/4-768x1024.jpg`,
  "Nisha Kaushik": `${base}/4-768x1024.jpg`,
  "Dr. Monika Ray Patnaik": `${base}/2-768x1024.jpg`,
  "Monika Ray Patnaik": `${base}/2-768x1024.jpg`,
  "Leepika Patnaik": `${base}/Untitled-design-27-1024x683.jpg`,
  "Akul Nayak": `${base}/Untitled-design-29-1024x683.jpg`,
  "Shri Kanak Vardhan Singh Deo": `${base}/IMG-2138.jpg`,
  "Kanak Vardhan Singh Deo": `${base}/IMG-2138.jpg`,
  "Shri Akash Das Nayak": `${base}/IMG-2287.jpg`,
  "Akash Das Nayak": `${base}/IMG-2287.jpg`,
};

export const brandLogo = `${base}/Whats-App-Image-2025-07-08-at-16-56-45-28b2319b.jpg`;

export const awardTrophies: Record<string, string> = {
  "SSI Karna Award": `${base}/ssikaranaaward-1024x982.png`,
  "Milkha Singh Sprint Champion": `${base}/ssimilkhasinghaward-1024x995.png`,
  "Dilip Tirkey Hockey Player": `${base}/ssidiliptirkygrassrootaward-1024x990-1.png`,
  "Paika Team Award": `${base}/ssiptushaaward-1024x973.png`,
  "SSI Sports Journalism": `${base}/ssisportsjournalismaward-300x284-1.png`,
};

export const eventMoments = [
  { src: `${base}/img_2107-m7VDV4nzBQU7PNZO.JPG`, alt: "Guests and awardees at the SSI Sports Awards ceremony" },
  { src: `${base}/img_2133-mp848ExLyOtPk9bX.JPG`, alt: "A moment from the SSI Sports Awards stage" },
  { src: `${base}/img_2157-mxB2BnD501sVoErK.JPG`, alt: "Award presentation at the SSI Sports Awards" },
  { src: `${base}/img_2171-mxB2BnLkjEID6qgl.JPG`, alt: "The SSI Sports Awards ceremony in progress" },
  { src: `${base}/img_2255-dJoPokM7KyC0q4P2.JPG`, alt: "Attendees at the SSI Sports Awards conclave" },
  { src: `${base}/img_2298-mv0P06Oen8Cvn680.JPG`, alt: "A celebratory moment from the awards evening" },
  { src: `${base}/IMG-2138.jpg`, alt: "Guests at the SSI Sports Awards" },
  { src: `${base}/IMG-2178.jpg`, alt: "The SSI Sports Awards audience" },
  { src: `${base}/IMG-2192.jpg`, alt: "Award recipients at the SSI Sports Awards" },
  { src: `${base}/IMG-2269.jpg`, alt: "The SSI Sports Awards celebration" },
  { src: `${base}/6K4A0381.jpg`, alt: "Highlights from the SSI Sports Awards" },
  { src: `${base}/6K4A0555.jpg`, alt: "The SSI Sports Awards on stage" },
];
